import { ApplicationConfig } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import {
  LucideBell,
  LucideBookOpen,
  LucideBot,
  LucideBuilding2,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleAlert,
  LucideClipboardCheck,
  LucideDownload,
  LucideExternalLink,
  LucideFileText,
  LucideFilter,
  LucideFolder,
  LucideHome,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLink,
  LucideMaximize2,
  LucideMessageSquare,
  LucideMoreHorizontal,
  LucidePaperclip,
  LucidePencil,
  LucidePlus,
  LucideSearch,
  LucideSend,
  LucideSettings,
  LucideShieldCheck,
  LucideSparkles,
  LucideUpload,
  LucideZap,
  provideLucideIcons,
} from '@lucide/angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(),
    provideLucideIcons(
      LucideBell,
      LucideBookOpen,
      LucideBot,
      LucideBuilding2,
      LucideCheck,
      LucideChevronDown,
      LucideChevronRight,
      LucideCircleAlert,
      LucideClipboardCheck,
      LucideDownload,
      LucideExternalLink,
      LucideFileText,
      LucideFilter,
      LucideFolder,
      LucideHome,
      LucideLayers,
      LucideLayoutDashboard,
      LucideLink,
      LucideMaximize2,
      LucideMessageSquare,
      LucideMoreHorizontal,
      LucidePaperclip,
      LucidePencil,
      LucidePlus,
      LucideSearch,
      LucideSend,
      LucideSettings,
      LucideShieldCheck,
      LucideSparkles,
      LucideUpload,
      LucideZap,
    ),
  ]
};
